when:
  branch: main

labels:
  backend: local
  platform: linux/amd64

steps:
  - name: setup attic
    image: bash
    commands:
      - attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default
    secrets: [attic_key]

  - name: run nixpkgs-review
    image: bash
    commands:
      - git clone https://github.com/NixOS/nixpkgs.git --depth 1
      - cd nixpkgs
      - nix run nixpkgs#nixpkgs-review -- pr 287455 --run 'attic push nix-cache result'

  # - name: push result
  #   image: bash
  #   commands:
  #     - attic push nix-cache result
